const Encryption = require('./encryption.js');

const password = '.0x304dh3761ga3.';

const message = 
    `
    VRIKVkNBCBwRDUJDEgQfDEpZC0dRWgcNEQ0EBEtDR1xBXwhAEg4/ExFUWVUCQwkbHgFIAwEEVUQRVlteEg9HDBQBQAMABFREEWhfVUVbERgfVUgAVgcBCgcHBwAGU1AaHVMcAQYAVUpOG00TBA5XSwwKTQMBBFRZAwEaEwYMXFtARFoJBAZUWAMHGhM4CFcMFBJOB1UGU14BUVcBUwNWHh1VQFJVV1BaUQEUTEsaEU1BVB0RCgFUWQMHBAFRTRFPQ18NXUQWXl8CAwQdRT5aSgwKWgUEUQUJAgNQVVBVURlLAR5SUgdcUFEPAxMaTUgMTV8cVhIOUVgCBwYCV1cfDE9dF0ZeQEZSCgACAlNTHwxxWRwRChZSXQZWVwRfUgRLSggbUgAAAQkLVFIJBlQRU3McWkBRQgE8QVhZQRRDCXV1S1pQX1ABSgkCBgBXUQAeGBxaUl1bEQZHFQwCUlEDHgISC1ZcUQccEQ0GHUU+WkoMCloFBgFWXVVSVwUCAAMcGwBMUFJRAFkDAlMTGjwfdVUSG1xUUUZSBgcHAVdSAxgCEhleX0EKHBENAANXUQMCDEMdX1VXEEoJBxoTOAhXDBQSTgUFBwdeUgVXCFZZCkoZA0oBBwICDgcDFEw6TWhVDFMXV1UWXl0DBgYBVFEFAgxRFVxFWhBKCQYEBFdRAwIMQx1fVVcQSgkHGhM4CFcMFBJOBQUHB15RVgcEVVQKSE1VSQsDBFxeCg4UTDpNaFUMUxdXVRZeXQMGBgFUUQUCDFEVXEVaEEoJBQMBV1EDAgxDHV9VVxBKCQcaEzgIVwwUEk4FBQZSWAEBAgZXUgZKHgNNAFYNBVgCUxRMOjwfDENRClBYYB0YVhUMA0tDVUEMCgMRb10ASgkVAAZSVwAbG1FBUAQEV1sGAVUBVlZSHU0JWh8SWAsLEQ1tBV5NAh4cCVQCAAZXNR8VWlQRBF8MFANLHxJXCwxWFQwDV1IDHh8ASR8SWwcLRkdfVANDCVUMWRwRChZSWVIDAAhXBFYWHQlAAwBXU18CDgUEAwARAgxDDFJCQAEMEQ0UA1dTBwMfAlUDCWBUWAkGBgtXUx0dFwQiERwWFwNaWRQLVlEEHh0ASAIcFhcDWllxQwYFVgwUA1QRXlUJDRENFHUGE0dGeFEcVkIDU0ofFUFeFQ1XZ0oSQgcJSUhKQENXRQJDCR9THFpdRVkpCUFUXhNdUR8MQEUVflFMMBpcWEZCRVseHwISG0ZCRgEGR2NEXggRQAwUHUkfElkFEGdFWV4XEhEUAwEF
    `;

const encryption = new Encryption();

const runExample = async () => {
    try {
        const decrypted = await encryption.decryptBase64(message);
        // console.log('Decrypted Base64:', decrypted);

        const decryptedXor = await encryption.decryptXor(decrypted, password);
        console.log('Decrypted XOR:', decryptedXor);
    } catch (error) {
        console.error('Error during decryption:', error);
        throw error;
    }
};

runExample().then(() => process.exit(0)).catch(() => process.exit(1));